server:
  port: 8081

spring:
  datasource.primary:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_data?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    filters: stat,wall,log4j

logging:
  file: springboot.log
  level:
    org:
      mybatis: TRACE
      springframework: INFO
    online:
      zhaopei:
        mypoject: TRACE
